/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controller.Controller;
import java.awt.Color;
import java.awt.GridLayout;
import java.io.IOException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import model.DeleteVertexActionResult;
import model.Edge;
import model.Vertex;

/**
 *
 * @author theph
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    GraphDisplayFrame graphDisplay;
    Controller controller;
    int step;

    public MainWindow() {
        initComponents();
        controller = new Controller();
        drawingPanel.setLayout(new GridLayout(1, 1));
        graphDisplay = new GraphDisplayFrame();

        graphDisplay.setBackground(Color.WHITE);
        drawingPanel.add(graphDisplay);
        graphDisplay.init(controller.graph);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        drawingPanel = new javax.swing.JPanel();
        tpanelFunction = new javax.swing.JTabbedPane();
        panelConstruct = new javax.swing.JPanel();
        panelAddVertex = new javax.swing.JPanel();
        lblNameAddV = new javax.swing.JLabel();
        btnAddVertex = new javax.swing.JButton();
        txtNameAddV = new javax.swing.JTextField();
        panelAddEdge = new javax.swing.JPanel();
        btnAddEdge = new javax.swing.JButton();
        lblFromAddE = new javax.swing.JLabel();
        txtFromAddE = new javax.swing.JTextField();
        lblToAddE = new javax.swing.JLabel();
        txtToAddE = new javax.swing.JTextField();
        lblCapacityAddE = new javax.swing.JLabel();
        txtCapacityAddE = new javax.swing.JTextField();
        panelDeleteVertex = new javax.swing.JPanel();
        btnDeleteVertex = new javax.swing.JButton();
        lblNameDeleteV = new javax.swing.JLabel();
        txtNameDeleteV = new javax.swing.JTextField();
        panelDeleteEdge = new javax.swing.JPanel();
        btnDeleteEdge = new javax.swing.JButton();
        lblFromDeleteE = new javax.swing.JLabel();
        txtFromDeleteE = new javax.swing.JTextField();
        lblToDeleteE = new javax.swing.JLabel();
        txtToDeleteE = new javax.swing.JTextField();
        lblAddV = new javax.swing.JLabel();
        lblAddE = new javax.swing.JLabel();
        lblDeleteV = new javax.swing.JLabel();
        lblDeleteE = new javax.swing.JLabel();
        lblMarkSS = new javax.swing.JLabel();
        panelMarkSS = new javax.swing.JPanel();
        btnMarkSource = new javax.swing.JButton();
        lblNameMarkSS = new javax.swing.JLabel();
        txtNameMarkSS = new javax.swing.JTextField();
        btnMarkSink = new javax.swing.JButton();
        panelRun = new javax.swing.JPanel();
        btnRun = new javax.swing.JButton();
        lblRunStatus = new javax.swing.JLabel();
        panelStepNav = new javax.swing.JPanel();
        btnPrevStep = new javax.swing.JButton();
        btnNextStep = new javax.swing.JButton();
        lblStep = new javax.swing.JLabel();
        panelLog = new javax.swing.JPanel();
        scrLog = new javax.swing.JScrollPane();
        txtLog = new javax.swing.JTextArea();
        menuBar = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        mnLoad = new javax.swing.JMenuItem();
        mnSave = new javax.swing.JMenuItem();
        separator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        mnAbout = new javax.swing.JMenu();
        mnAboutProg = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        drawingPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout drawingPanelLayout = new javax.swing.GroupLayout(drawingPanel);
        drawingPanel.setLayout(drawingPanelLayout);
        drawingPanelLayout.setHorizontalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 445, Short.MAX_VALUE)
        );
        drawingPanelLayout.setVerticalGroup(
            drawingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        panelAddVertex.setName(""); // NOI18N

        lblNameAddV.setText("Name");

        btnAddVertex.setLabel("Add vertex");
        btnAddVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddVertexActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelAddVertexLayout = new javax.swing.GroupLayout(panelAddVertex);
        panelAddVertex.setLayout(panelAddVertexLayout);
        panelAddVertexLayout.setHorizontalGroup(
            panelAddVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddVertexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddVertex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAddVertexLayout.createSequentialGroup()
                        .addComponent(lblNameAddV)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameAddV)))
                .addContainerGap())
        );
        panelAddVertexLayout.setVerticalGroup(
            panelAddVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddVertexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameAddV)
                    .addComponent(txtNameAddV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAddVertex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAddVertex.getAccessibleContext().setAccessibleName("");
        btnAddVertex.getAccessibleContext().setAccessibleDescription("");

        btnAddEdge.setLabel("Add edge");
        btnAddEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddEdgeActionPerformed(evt);
            }
        });

        lblFromAddE.setText("From");

        lblToAddE.setText("To");

        lblCapacityAddE.setText("Capacity");

        javax.swing.GroupLayout panelAddEdgeLayout = new javax.swing.GroupLayout(panelAddEdge);
        panelAddEdge.setLayout(panelAddEdgeLayout);
        panelAddEdgeLayout.setHorizontalGroup(
            panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAddEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelAddEdgeLayout.createSequentialGroup()
                        .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFromAddE)
                            .addComponent(lblToAddE))
                        .addGap(28, 28, 28)
                        .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToAddE)
                            .addComponent(txtFromAddE)))
                    .addGroup(panelAddEdgeLayout.createSequentialGroup()
                        .addComponent(lblCapacityAddE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtCapacityAddE)))
                .addContainerGap())
        );
        panelAddEdgeLayout.setVerticalGroup(
            panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAddEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFromAddE)
                    .addComponent(txtFromAddE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToAddE)
                    .addComponent(txtToAddE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelAddEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCapacityAddE)
                    .addComponent(txtCapacityAddE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAddEdge)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDeleteVertex.setLabel("Delete Vertex");
        btnDeleteVertex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteVertexActionPerformed(evt);
            }
        });

        lblNameDeleteV.setText("Name");

        javax.swing.GroupLayout panelDeleteVertexLayout = new javax.swing.GroupLayout(panelDeleteVertex);
        panelDeleteVertex.setLayout(panelDeleteVertexLayout);
        panelDeleteVertexLayout.setHorizontalGroup(
            panelDeleteVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteVertexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDeleteVertex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDeleteVertexLayout.createSequentialGroup()
                        .addComponent(lblNameDeleteV)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameDeleteV, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        panelDeleteVertexLayout.setVerticalGroup(
            panelDeleteVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteVertexLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteVertexLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameDeleteV)
                    .addComponent(txtNameDeleteV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteVertex)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnDeleteEdge.setLabel("Delete edge");
        btnDeleteEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteEdgeActionPerformed(evt);
            }
        });

        lblFromDeleteE.setText("From");
        lblFromDeleteE.setToolTipText("");

        lblToDeleteE.setText("To");

        javax.swing.GroupLayout panelDeleteEdgeLayout = new javax.swing.GroupLayout(panelDeleteEdge);
        panelDeleteEdge.setLayout(panelDeleteEdgeLayout);
        panelDeleteEdgeLayout.setHorizontalGroup(
            panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDeleteEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelDeleteEdgeLayout.createSequentialGroup()
                        .addGroup(panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFromDeleteE)
                            .addComponent(lblToDeleteE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtToDeleteE)
                            .addComponent(txtFromDeleteE))))
                .addContainerGap())
        );
        panelDeleteEdgeLayout.setVerticalGroup(
            panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDeleteEdgeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFromDeleteE)
                    .addComponent(txtFromDeleteE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDeleteEdgeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblToDeleteE)
                    .addComponent(txtToDeleteE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteEdge)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        lblAddV.setText("Add vertex");

        lblAddE.setText("Add edge");

        lblDeleteV.setText("Delete vertex");

        lblDeleteE.setText("Delete edge");

        lblMarkSS.setText("Mark source/sink");

        btnMarkSource.setText("Mark Source");
        btnMarkSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkSourceActionPerformed(evt);
            }
        });

        lblNameMarkSS.setText("Name");

        btnMarkSink.setLabel("Mark Sink");
        btnMarkSink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMarkSinkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMarkSSLayout = new javax.swing.GroupLayout(panelMarkSS);
        panelMarkSS.setLayout(panelMarkSSLayout);
        panelMarkSSLayout.setHorizontalGroup(
            panelMarkSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarkSSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarkSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMarkSSLayout.createSequentialGroup()
                        .addComponent(lblNameMarkSS)
                        .addGap(18, 18, 18)
                        .addComponent(txtNameMarkSS))
                    .addComponent(btnMarkSource, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMarkSink, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelMarkSSLayout.setVerticalGroup(
            panelMarkSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMarkSSLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelMarkSSLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNameMarkSS)
                    .addComponent(txtNameMarkSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarkSource)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnMarkSink)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelConstructLayout = new javax.swing.GroupLayout(panelConstruct);
        panelConstruct.setLayout(panelConstructLayout);
        panelConstructLayout.setHorizontalGroup(
            panelConstructLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConstructLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelConstructLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelDeleteEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAddVertex, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelAddEdge, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelConstructLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(panelDeleteVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelConstructLayout.createSequentialGroup()
                        .addGroup(panelConstructLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAddV)
                            .addComponent(lblAddE)
                            .addComponent(lblDeleteV)
                            .addComponent(lblDeleteE)
                            .addComponent(lblMarkSS))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(panelMarkSS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelConstructLayout.setVerticalGroup(
            panelConstructLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConstructLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAddV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(lblAddE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelAddEdge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeleteV)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeleteVertex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeleteE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelDeleteEdge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblMarkSS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelMarkSS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );

        tpanelFunction.addTab("Construct", panelConstruct);

        btnRun.setLabel("Run");
        btnRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRunActionPerformed(evt);
            }
        });

        lblRunStatus.setText("Run Status");

        btnPrevStep.setText("Previous");
        btnPrevStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrevStepActionPerformed(evt);
            }
        });

        btnNextStep.setText("Next");
        btnNextStep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextStepActionPerformed(evt);
            }
        });

        lblStep.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStep.setText("step / total_step");
        lblStep.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout panelStepNavLayout = new javax.swing.GroupLayout(panelStepNav);
        panelStepNav.setLayout(panelStepNavLayout);
        panelStepNavLayout.setHorizontalGroup(
            panelStepNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepNavLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnPrevStep)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStep, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNextStep)
                .addContainerGap())
        );
        panelStepNavLayout.setVerticalGroup(
            panelStepNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelStepNavLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelStepNavLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPrevStep)
                    .addComponent(btnNextStep)
                    .addComponent(lblStep))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelRunLayout = new javax.swing.GroupLayout(panelRun);
        panelRun.setLayout(panelRunLayout);
        panelRunLayout.setHorizontalGroup(
            panelRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRunLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelRunLayout.createSequentialGroup()
                        .addComponent(lblRunStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 8, Short.MAX_VALUE))
                    .addComponent(btnRun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelStepNav, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelRunLayout.setVerticalGroup(
            panelRunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnRun)
                .addGap(18, 18, 18)
                .addComponent(lblRunStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelStepNav, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(497, Short.MAX_VALUE))
        );

        tpanelFunction.addTab("Run", panelRun);

        txtLog.setColumns(20);
        txtLog.setRows(5);
        scrLog.setViewportView(txtLog);

        javax.swing.GroupLayout panelLogLayout = new javax.swing.GroupLayout(panelLog);
        panelLog.setLayout(panelLogLayout);
        panelLogLayout.setHorizontalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrLog, javax.swing.GroupLayout.DEFAULT_SIZE, 298, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelLogLayout.setVerticalGroup(
            panelLogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLogLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrLog, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE)
                .addContainerGap())
        );

        tpanelFunction.addTab("Log", panelLog);

        mnFile.setText("File");

        mnLoad.setText("Load");
        mnLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLoadActionPerformed(evt);
            }
        });
        mnFile.add(mnLoad);

        mnSave.setText("Save");
        mnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSaveActionPerformed(evt);
            }
        });
        mnFile.add(mnSave);
        mnFile.add(separator1);

        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnFile.add(mnExit);

        menuBar.add(mnFile);

        mnAbout.setText("About");

        mnAboutProg.setText("About");
        mnAboutProg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAboutProgActionPerformed(evt);
            }
        });
        mnAbout.add(mnAboutProg);

        menuBar.add(mnAbout);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(drawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpanelFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tpanelFunction)
                    .addComponent(drawingPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tpanelFunction.getAccessibleContext().setAccessibleName("Run");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    void reloadStepDisplay() {
        lblStep.setText(step + "/" + controller.getNumberOfStep());
    }

    void goToStep(int step) {
        this.step = step;
        this.reloadStepDisplay();
        graphDisplay.loadStepGraph(controller.getStep(step));
        graphDisplay.repaint();
    }


    private void mnLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLoadActionPerformed
        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "JPG & GIF Images", "jpg", "gif");
//        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                controller.loadFile(chooser.getSelectedFile().getAbsolutePath());
                graphDisplay.init(controller.graph);
                graphDisplay.repaint();
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnLoadActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSaveActionPerformed
        JFileChooser chooser = new JFileChooser();
//        FileNameExtensionFilter filter = new FileNameExtensionFilter(
//                "JPG & GIF Images", "jpg", "gif");
//        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            try {
                controller.saveFile(chooser.getSelectedFile().getName());
            } catch (IOException ex) {
                Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_mnSaveActionPerformed

    private void btnPrevStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrevStepActionPerformed
        if (step > 1) {
            step--;
            goToStep(step);
        }
    }//GEN-LAST:event_btnPrevStepActionPerformed

    private void btnNextStepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextStepActionPerformed
        if (step < controller.getNumberOfStep()) {
            step++;
            goToStep(step);
        }
    }//GEN-LAST:event_btnNextStepActionPerformed

    private void btnRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRunActionPerformed
        try {
            long time = System.currentTimeMillis();
            controller.process();
            long duration = System.currentTimeMillis() - time;
            lblRunStatus.setText("Run status: Completed in " + (duration / 1000) + "s");
            goToStep(controller.getNumberOfStep());
        } catch (Exception ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Graph invalid");
            return;
        }
    }//GEN-LAST:event_btnRunActionPerformed

    private void btnAddVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddVertexActionPerformed
        String content = txtNameAddV.getText();
        // TODO: check if vertex with same name already exist
        if(content.length()>0){
            Vertex newV = controller.addVertex(content);
            graphDisplay.addVertex(newV);
        }
        
    }//GEN-LAST:event_btnAddVertexActionPerformed

    private void btnAddEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddEdgeActionPerformed
        String from = txtFromAddE.getText();
        String to = txtToAddE.getText();
        int capacity;
        try {
            capacity = Integer.parseInt(txtCapacityAddE.getText());
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Capacity must be a number");
            return;
        }
        try{
            Edge newE = controller.addEdge(from, to, capacity);
            graphDisplay.addEdge(newE);
        }catch(VertexNotFoundException ex){
            JOptionPane.showMessageDialog(this, "Vertex not found");
            return;
        }
        
    }//GEN-LAST:event_btnAddEdgeActionPerformed

    private void btnDeleteVertexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteVertexActionPerformed
        String name = txtNameDeleteV.getText();
        try {
            DeleteVertexActionResult result = controller.deleteVertex(name);
            graphDisplay.deleteVertex(result.getDeleted());
            graphDisplay.deleteEdges(result.getAffectedEdges());
        } catch (VertexNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteVertexActionPerformed

    private void btnDeleteEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteEdgeActionPerformed
        String from = txtFromDeleteE.getText();
        String to = txtToDeleteE.getText();
        
        try {
            controller.deleteEdge(from, to);
        } catch (VertexNotFoundException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteEdgeActionPerformed

    private void btnMarkSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkSourceActionPerformed
        String name = txtNameMarkSS.getText();
        controller.setSource(name);
        JOptionPane.showMessageDialog(this, "Completed");
    }//GEN-LAST:event_btnMarkSourceActionPerformed

    private void btnMarkSinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMarkSinkActionPerformed
        String name = txtNameMarkSS.getText();
        controller.setSink(name);
        JOptionPane.showMessageDialog(this, "Completed");
    }//GEN-LAST:event_btnMarkSinkActionPerformed

    private void mnAboutProgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAboutProgActionPerformed
        new AboutDialog(this,true).setVisible(true);
    }//GEN-LAST:event_mnAboutProgActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddEdge;
    private javax.swing.JButton btnAddVertex;
    private javax.swing.JButton btnDeleteEdge;
    private javax.swing.JButton btnDeleteVertex;
    private javax.swing.JButton btnMarkSink;
    private javax.swing.JButton btnMarkSource;
    private javax.swing.JButton btnNextStep;
    private javax.swing.JButton btnPrevStep;
    private javax.swing.JButton btnRun;
    private javax.swing.JPanel drawingPanel;
    private javax.swing.JLabel lblAddE;
    private javax.swing.JLabel lblAddV;
    private javax.swing.JLabel lblCapacityAddE;
    private javax.swing.JLabel lblDeleteE;
    private javax.swing.JLabel lblDeleteV;
    private javax.swing.JLabel lblFromAddE;
    private javax.swing.JLabel lblFromDeleteE;
    private javax.swing.JLabel lblMarkSS;
    private javax.swing.JLabel lblNameAddV;
    private javax.swing.JLabel lblNameDeleteV;
    private javax.swing.JLabel lblNameMarkSS;
    private javax.swing.JLabel lblRunStatus;
    private javax.swing.JLabel lblStep;
    private javax.swing.JLabel lblToAddE;
    private javax.swing.JLabel lblToDeleteE;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu mnAbout;
    private javax.swing.JMenuItem mnAboutProg;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenuItem mnLoad;
    private javax.swing.JMenuItem mnSave;
    private javax.swing.JPanel panelAddEdge;
    private javax.swing.JPanel panelAddVertex;
    private javax.swing.JPanel panelConstruct;
    private javax.swing.JPanel panelDeleteEdge;
    private javax.swing.JPanel panelDeleteVertex;
    private javax.swing.JPanel panelLog;
    private javax.swing.JPanel panelMarkSS;
    private javax.swing.JPanel panelRun;
    private javax.swing.JPanel panelStepNav;
    private javax.swing.JScrollPane scrLog;
    private javax.swing.JPopupMenu.Separator separator1;
    private javax.swing.JTabbedPane tpanelFunction;
    private javax.swing.JTextField txtCapacityAddE;
    private javax.swing.JTextField txtFromAddE;
    private javax.swing.JTextField txtFromDeleteE;
    private javax.swing.JTextArea txtLog;
    private javax.swing.JTextField txtNameAddV;
    private javax.swing.JTextField txtNameDeleteV;
    private javax.swing.JTextField txtNameMarkSS;
    private javax.swing.JTextField txtToAddE;
    private javax.swing.JTextField txtToDeleteE;
    // End of variables declaration//GEN-END:variables
}
